version: "3.7"
services:
  db:
    container_name: postgres-service
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  database-data:

